# Generated by Django 5.2.4 on 2025-07-26 18:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitystatus',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
